
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=IGroceryStoreDb
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432